"""empty message

Revision ID: 411025f3cdb8
Revises: 
Create Date: 2024-03-26 16:53:51.115188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411025f3cdb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cats')
    # ### end Alembic commands ###
